-- auto-generated definition
create table event
(
    id            bigint generated by default as identity
        constraint event_pkey
            primary key,
    event_content text not null,
);

alter table event
    owner to postgres;

